### ISSUE TITLE
Kadane's Algorithm 

### ISSUE THREAD

**Issue by rahulsrivastava1** [rahulsrivastava1/DSA-BASKET#1]

**Comment by shivanshjaitly** [comment]
Hey @rahulsrivastava1   I noticed one algorithm that is Kadanen's algorigthm with optimal approach is there. So I guess your need will be completed. Can I?

**Comment by rahulsrivastava1** [comment]
> Hey @rahulsrivastava1 I noticed one algorithm that is Kadanen's algorigthm with optimal approach is there. So I guess your need will be completed. Can I?

Yes, sure you can do it!
